baseURL = 'https://jamesplank.co.uk/'
languageCode = 'en-us'
title = 'James Plank'
sectionPagesMenu = 'main'

[params]
    author = 'James Plank'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true